### ISSUE TITLE
Update Region of Veto Preferences

### ISSUE THREAD

**Issue by crashzk** [repeekgg/browser-extension#125]
We currently only have 3 regions to choose from.

![image](https://user-images.githubusercontent.com/32937653/198856020-8c199088-29ae-4cae-8fb6-18c400906e7a.png)

However, on the FACEIT platform there are 5 in total, **SA** and **SEA** are missing, would it be possible to add them?

![image](https://user-images.githubusercontent.com/32937653/198855989-797edbfe-01b2-4f05-84a8-9ff1dd7063e6.png)

**Comment by timche** [comment]
SEA and SA only have 1 server, Singapore and São Paulo respectively.

**Comment by crashzk** [comment]
Ok, and which of the options should I select in the extension to configure for my location, Brazil, São Paulo?

![image](https://github.com/repeekgg/browser-extension/assets/32937653/afaf9dad-75fb-4d21-80ee-6093fb51fb84)

**Comment by timche** [comment]
There isn't really anything to configure if Brazil only has 1 server location, unless I'm missing something?
