### ISSUE TITLE
faceit update broke auto accept

### ISSUE THREAD

**Issue by ogmicco** [repeekgg/browser-extension#139]
title

**Comment by Gumbosveins** [comment]
I tried pusing a fix but I don't have permission to push a new branch. 
@timche can you give me access to push new branch and create a pull request?

**Comment by QGIsK** [comment]
@Gumbosveins You should be able to fork it and then make a pull request

**Comment by Gumbosveins** [comment]
I cloned it and could not push a new branch

**Comment by QGIsK** [comment]
You need to fork it first, clone that repository and then you should be able to create a pull request from your own repository ( Into this one )

**Comment by ersitan** [comment]
> I tried pusing a fix but I don't have permission to push a new branch. @timche can you give me permission to push new branch and create a pull request?

can you maybe share the code? so that someone can actually make a pr?

**Comment by QGIsK** [comment]
Seems he fixed it, see https://github.com/faceit-enhancer/faceit-enhancer/commit/2fba0cc641675a3d43c1e2cc77e21f2670d65c09

**Comment by mfatihsaglam** [comment]
Sometimes still won't accept match. I have many times "DID NOT ACCEPT MATCH" bans in a row. Last time I had 2.5 hours ban.
