### ISSUE TITLE
Painfully slow firefox update approval times

### ISSUE THREAD

**Issue by Lidbetter** [repeekgg/browser-extension#144]
Hey,

Thanks for making the extension available on firefox.
I understand that the slow update times are because the mozilla addon store does not immediately approve them for distribution.

While it is not your fault, it is still frustrating to have the extension broken for days/weeks while waiting on the mozilla addon store.

It should be possible to upload the `xpi` asset as part of the release process and generate the needed update manifest file (and host it on github pages [or some other solution to have it end up on `repeek.gg`])

https://extensionworkshop.com/documentation/manage/updating-your-extension/#enable-update

Is this something you could consider doing?

Thanks <3

**Comment by timche** [comment]
Thanks for sharing this! Trust me, this annoys me as much as it is for everyone else. I'll have a look into this and maybe go with it.

**Comment by Lidbetter** [comment]
If auto update isn't possible/will take a more time to do the way you want.

A good interim step would be to make the xpi available as part of the release action, this would mean I could manually update without needing to have node, npm, etc. installed on my windows machine to build it

**Comment by kyle0r** [comment]
👍 +1 for making the xpi available in releases - at least then users can manually install an update?. I feel its a good workaround until something else more robust comes along. Is there somewhere I can read about why Mozilla addons are so slow in releasing updates, that seems like a step backwards? Feeling out-of-the-loop.

footnote: @timche thanks for creating and sharing your awesome extension ♥😊

**Comment by timche** [comment]
I understand your guys frustration. Reviews are being done by humans and therefore it takes much longer than on Chrome. Not much I can do about it on that side. 

I'll look into the alternatives once I'm back from my holiday. 

Thanks for your patience 🙏

**Comment by timche** [comment]
Good news: The latest version 3.1.16 just got approved and released on Firefox!

**Comment by kyle0r** [comment]
@Lidbetter @timche please can you clarify why this is now closed? I wasn't aware a solution was found to the slow Firefox release times and was hoping for xpi releases or something similar?

**Comment by Lidbetter** [comment]
Closed to tidy up my open issues.

This seems to be in the hands of Firefox - unless something changes on their end, the speed of updates is what it is.

**Comment by timche** [comment]
I've started attaching the XPI file in the Repeek Discord server in #releases. If you aren't on the server yet, you can join using this link: https://rpk.gg/discord.
