### ISSUE TITLE
Elo for CS2 should be adjusted according to a new schema

### ISSUE THREAD

**Issue by noxterr** [repeekgg/browser-extension#146]
Hello!
This is the new CS2 Elo skill level distribution: https://support.faceit.com/hc/en-us/articles/10525200579740

The system should be identifying and correcting that in order to not have certain issues like [this screen](https://cdn.discordapp.com/attachments/805852393245245471/1154887957623349308/image.png)

Sorry for the short written issue, but is simple to describe

**Comment by mrubio7** [comment]
#147
