### ISSUE TITLE
ELO progress bar on profile showing incorrect levels for CS:GO

### ISSUE THREAD

**Issue by ivolong** [repeekgg/browser-extension#153]
hey,

i notice that ELO boundaries are correctly defined [here](https://github.com/repeekgg/browser-extension/blob/d956c70df9f4e1a0c5a3498bbe585114abe6729f/src/content/helpers/elo.js#L41) but are not reflected on the level progress bar under profile stats for CS:GO

steps to replicate:

1. go to https://www.faceit.com/en/players/ivolong/stats/csgo
2. ELO should read 1579 (correct), but level progress bar displays Level 8 (incorrect) (in csgo i was level 7)
3. change game to CS2 via dropdown
4. ELO should read 1573 (correct) and level progress bar display Level 8 (correct) (in cs2)

best,
ivo

**Comment by leedrum** [comment]
@ivolong in the level progress bar, it includes the game type(csgo or cs2). I think lv8 is displayed for cs2.

**Comment by ivolong** [comment]
> @ivolong in the level progress bar, it includes the game type(csgo or cs2). I think lv8 is displayed for cs2.

yes, but level 8 is also displayed for csgo, which is incorrect

**Comment by leedrum** [comment]
@ivolong the level progress will not be changed when switching the game.

**Comment by timche** [comment]
Thanks for reporting this issue @ivolong! Since CS:GO is considered legacy, I won't prioritize this as a bug.
